name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.4.0]

    steps:
    - uses: actions/checkout@v3

    # Clear npm cache
    - name: Clear npm cache
      run: npm cache clean -f

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Debugging steps
    - name: Display Node.js version
      run: node -v

    - name: Display npm version
      run: npm -v

    - name: List files in the directory
      run: ls -l

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Your existing npm ci step
    # - run: npm ci
