name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.4.0]

    steps:
    - uses: actions/checkout@v3

    # Set working directory
    - name: Set working directory
      working-directory: /home/ubuntu/react_portfolio/_work/portfolio-aws/portfolio-aws

    # Clear npm cache
    - name: Clear npm cache
      run: npm cache clean -f

    # Grant permissions to the directory
    - name: Grant permissions to the directory
      run: sudo chmod -R 755 dist/assets

    # Change ownership of the directory
    - name: Change ownership of the directory
      run: sudo chown -R $USER:$USER dist/assets

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Debugging steps
    - name: Display Node.js version
      run: node -v

    - name: Display npm version
      run: npm -v

    - name: List files in the directory
      run: ls -l

    # Install dependencies
    - name: Install dependencies
      run: npm install
